# Workflow name.
name: prerequisites
# Workflow trigger.
on: [pull_request, push, workflow_dispatch]
# Jobs to run on workflow.
jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    # Steps to run on this job.
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test if file exists
        shell: pwsh
        # When testing for a file the exact case is required.
        run: Test-Path ./pyproject.toml | Should -Be $true